"""Initial database setup with summoners, matches, and champion masteries

Revision ID: 23891b733c83
Revises: 
Create Date: 2025-08-28 10:50:56.918609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23891b733c83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('game_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('game_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('game_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('game_duration', sa.Integer(), nullable=False),
    sa.Column('game_mode', sa.String(), nullable=False),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.Column('game_version', sa.String(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.String(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('tournament_code', sa.String(), nullable=True),
    sa.Column('winning_team', sa.Integer(), nullable=True),
    sa.Column('teams_data', sa.JSON(), nullable=True),
    sa.Column('timeline_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_matches_game_creation'), 'matches', ['game_creation'], unique=False)
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=False)
    op.create_index(op.f('ix_matches_queue_id'), 'matches', ['queue_id'], unique=False)
    op.create_table('summoners',
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('tag_line', sa.String(), nullable=False),
    sa.Column('summoner_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('summoner_level', sa.Integer(), nullable=False),
    sa.Column('profile_icon_id', sa.Integer(), nullable=True),
    sa.Column('revision_date', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('puuid')
    )
    op.create_index(op.f('ix_summoners_game_name'), 'summoners', ['game_name'], unique=False)
    op.create_index(op.f('ix_summoners_puuid'), 'summoners', ['puuid'], unique=False)
    op.create_index(op.f('ix_summoners_summoner_id'), 'summoners', ['summoner_id'], unique=False)
    op.create_table('champion_masteries',
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=False),
    sa.Column('mastery_points', sa.Integer(), nullable=False),
    sa.Column('last_play_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('points_until_next_level', sa.Integer(), nullable=True),
    sa.Column('chest_granted', sa.Boolean(), nullable=True),
    sa.Column('tokens_earned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['puuid'], ['summoners.puuid'], ),
    sa.PrimaryKeyConstraint('puuid', 'champion_id')
    )
    op.create_index(op.f('ix_champion_masteries_puuid'), 'champion_masteries', ['puuid'], unique=False)
    op.create_table('match_participants',
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('champion_name', sa.String(), nullable=False),
    sa.Column('champion_level', sa.Integer(), nullable=False),
    sa.Column('summoner_spell_1', sa.Integer(), nullable=False),
    sa.Column('summoner_spell_2', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('double_kills', sa.Integer(), nullable=False),
    sa.Column('triple_kills', sa.Integer(), nullable=False),
    sa.Column('quadra_kills', sa.Integer(), nullable=False),
    sa.Column('penta_kills', sa.Integer(), nullable=False),
    sa.Column('total_damage_dealt', sa.Integer(), nullable=False),
    sa.Column('total_damage_dealt_to_champions', sa.Integer(), nullable=False),
    sa.Column('total_damage_taken', sa.Integer(), nullable=False),
    sa.Column('magic_damage_dealt', sa.Integer(), nullable=False),
    sa.Column('physical_damage_dealt', sa.Integer(), nullable=False),
    sa.Column('true_damage_dealt', sa.Integer(), nullable=False),
    sa.Column('gold_earned', sa.Integer(), nullable=False),
    sa.Column('total_minions_killed', sa.Integer(), nullable=False),
    sa.Column('neutral_minions_killed', sa.Integer(), nullable=False),
    sa.Column('vision_score', sa.Integer(), nullable=False),
    sa.Column('wards_placed', sa.Integer(), nullable=False),
    sa.Column('wards_killed', sa.Integer(), nullable=False),
    sa.Column('control_wards_purchased', sa.Integer(), nullable=False),
    sa.Column('turret_kills', sa.Integer(), nullable=False),
    sa.Column('inhibitor_kills', sa.Integer(), nullable=False),
    sa.Column('dragon_kills', sa.Integer(), nullable=False),
    sa.Column('baron_kills', sa.Integer(), nullable=False),
    sa.Column('largest_killing_spree', sa.Integer(), nullable=False),
    sa.Column('largest_multi_kill', sa.Integer(), nullable=False),
    sa.Column('total_time_cc_dealt', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['puuid'], ['summoners.puuid'], ),
    sa.PrimaryKeyConstraint('match_id', 'puuid')
    )
    op.create_index(op.f('ix_match_participants_champion_id'), 'match_participants', ['champion_id'], unique=False)
    op.create_index(op.f('ix_match_participants_puuid'), 'match_participants', ['puuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_participants_puuid'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_champion_id'), table_name='match_participants')
    op.drop_table('match_participants')
    op.drop_index(op.f('ix_champion_masteries_puuid'), table_name='champion_masteries')
    op.drop_table('champion_masteries')
    op.drop_index(op.f('ix_summoners_summoner_id'), table_name='summoners')
    op.drop_index(op.f('ix_summoners_puuid'), table_name='summoners')
    op.drop_index(op.f('ix_summoners_game_name'), table_name='summoners')
    op.drop_table('summoners')
    op.drop_index(op.f('ix_matches_queue_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_game_creation'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
